/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import accesoADatos.DietaData;
import entidades.Dieta;
import entidades.Paciente;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan
 */
public class GestionesDietas extends javax.swing.JPanel {

    /**
     * Creates new form GestionesDietas
     */
    public GestionesDietas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jbNueva = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jlDieta = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlPaciente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtPaciente = new javax.swing.JTextField();
        jtPesoInicial = new javax.swing.JTextField();
        jtPesoFinal = new javax.swing.JTextField();
        jtGenero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtAltura = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jdFechaFinal = new com.toedter.calendar.JDateChooser();
        jdFechaInicial = new com.toedter.calendar.JDateChooser();
        jlEstado = new javax.swing.JLabel();
        jrEstado = new javax.swing.JRadioButton();
        jtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtPesoBuscado = new javax.swing.JTextField();
        jbSalir = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setLayout(null);

        jPanel1.setLayout(null);

        jbNueva.setText("Nueva Dieta");
        jbNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevaActionPerformed(evt);
            }
        });
        jPanel1.add(jbNueva);
        jbNueva.setBounds(12, 395, 99, 25);

        jbGuardar.setText("Guardar Dieta");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jbGuardar);
        jbGuardar.setBounds(129, 395, 107, 25);

        jbEliminar.setText("Eliminar Dieta");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jbEliminar);
        jbEliminar.setBounds(248, 395, 107, 25);

        jlDieta.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jlDieta.setText("Gestion Dietas");
        jlDieta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jlDieta);
        jlDieta.setBounds(30, 10, 150, 30);

        jlNombre.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jlNombre.setText("Nombre");
        jPanel1.add(jlNombre);
        jlNombre.setBounds(87, 63, 70, 23);

        jlPaciente.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jlPaciente.setText("Paciente");
        jPanel1.add(jlPaciente);
        jlPaciente.setBounds(12, 105, 65, 23);

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel3.setText("Fecha Inicial");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(12, 142, 99, 23);

        jLabel4.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel4.setText("Peso Inicial");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(240, 140, 88, 23);

        jLabel5.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel5.setText("Peso Final");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(240, 180, 90, 16);

        jLabel6.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel6.setText("Genero");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(12, 231, 54, 23);

        jtPaciente.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.add(jtPaciente);
        jtPaciente.setBounds(170, 100, 134, 22);

        jtPesoInicial.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.add(jtPesoInicial);
        jtPesoInicial.setBounds(350, 140, 100, 22);

        jtPesoFinal.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.add(jtPesoFinal);
        jtPesoFinal.setBounds(350, 180, 100, 22);

        jtGenero.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.add(jtGenero);
        jtGenero.setBounds(130, 230, 80, 22);

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel1.setText("Altura");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(240, 230, 50, 20);

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel2.setText("FechaFinal");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(12, 185, 86, 23);

        jtAltura.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.add(jtAltura);
        jtAltura.setBounds(350, 230, 100, 22);

        jbBuscar.setText("Bucar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jbBuscar);
        jbBuscar.setBounds(350, 60, 65, 25);

        jdFechaFinal.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.add(jdFechaFinal);
        jdFechaFinal.setBounds(130, 180, 82, 22);

        jdFechaInicial.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.add(jdFechaInicial);
        jdFechaInicial.setBounds(130, 140, 82, 22);

        jlEstado.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jlEstado.setText("Estado");
        jPanel1.add(jlEstado);
        jlEstado.setBounds(10, 270, 70, 23);

        jrEstado.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.add(jrEstado);
        jrEstado.setBounds(130, 270, 21, 21);

        jtNombre.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.add(jtNombre);
        jtNombre.setBounds(170, 60, 135, 22);

        jLabel7.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel7.setText("Id");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(12, 63, 25, 23);

        jtId.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.add(jtId);
        jtId.setBounds(40, 60, 30, 22);

        jLabel8.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel8.setText("Peso Buscado");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(240, 270, 110, 23);

        jtPesoBuscado.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.add(jtPesoBuscado);
        jtPesoBuscado.setBounds(350, 270, 100, 22);

        jbSalir.setText("Salir");
        jPanel1.add(jbSalir);
        jbSalir.setBounds(362, 395, 57, 25);

        Fondo.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/green-682620_1280.jpg"))); // NOI18N
        jPanel1.add(Fondo);
        Fondo.setBounds(0, 0, 1000, 660);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 1002, 660);
    }// </editor-fold>//GEN-END:initComponents
private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {                                        
         
            dispose();
        
    }
    private void jbNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevaActionPerformed
        
        jtId.setText("");
        jtNombre.setText("");
        jtPaciente.setText("");
        jdFechaInicial.setDate(new java.util.Date());
        jtPesoInicial.setText("");
        jdFechaFinal.setDate(new java.util.Date());
        jtPesoFinal.setText("");
        jtGenero.setText("");
        jtAltura.setText("");
        jrEstado.setSelected(false);
        
        
    }//GEN-LAST:event_jbNuevaActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed

        DietaData dd = new DietaData();
        Dieta dieta = new Dieta();
        Paciente paci= new  Paciente();
        try {
            Integer id=Integer.parseInt(jtId.getText());
            dieta = dd.buscarDieta(id);
            jtNombre.setText(dieta.getNombre());
            jtPaciente.setText(paci.getNombre());
            jrEstado.setSelected(dieta.isEstado());
            LocalDate lc = dieta.getFechaInicial();
            java.util.Date date = java.util.Date.from(lc.atStartOfDay(ZoneId.systemDefault()).toInstant());
            jdFechaInicial.setDate(date);
            jtPesoInicial.setText(Double.toString((Double)dieta.getPesoInicial()));
            jdFechaFinal.setDate(date);
            jtPesoFinal.setText(Double.toString((Double)dieta.getPesoFinal()));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un dato valido");
        }

                                // TODO add your handling code here:
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed

        
        DietaData dd = new DietaData();
        Dieta dieta = null;
        Paciente paci=new Paciente();

        if (jtNombre.getText().isEmpty() || jdFechaInicial.getDate() == null || jtPesoInicial.getText().isEmpty()|| jdFechaFinal.getDate() == null) {
            JOptionPane.showMessageDialog(this, "no puede haber campos vacios");
            return;
        }
        try {
            java.util.Date fechaIni = jdFechaInicial.getDate();
            java.util.Date fechaFin = jdFechaFinal.getDate();
            LocalDate fechaInicial = fechaIni.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate fechaFinal = fechaFin.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
               Integer id=Integer.parseInt(jtId.getText());
               dieta = dd.buscarDieta(id);
                if (dieta == null) {
                    dieta = new Dieta();
                    dieta.setNombre(jtNombre.getText());
                    paci.setNombre(jtPaciente.getText());
                    dieta.setPaciente(paci);
                    dieta.setFechaInicial(fechaInicial);
                    dieta.setFechaFinal(fechaInicial);
                    dieta.setEstado(jrEstado.isSelected());
                    dd.guardarDieta(dieta);
                } else {
                    dieta.setNombre(jtNombre.getText());
                    dieta.setFechaInicial(fechaInicial);
                    dieta.setEstado(jrEstado.isSelected());
                    dd.modificarDieta(dieta);
                }

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero valido");
        }
       
        


    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
 if (jtNombre.getText().isEmpty())  {//seria id y nombre???
                JOptionPane.showMessageDialog(this, "no puede haber campos vacios");
                return;
        }
        try{
        
        DietaData ad = new DietaData();
        Dieta dieta = new Dieta();
        Integer id=Integer.parseInt(jtId.getText()); 

        dieta=ad.buscarDieta(id);
        if(dieta==null){
            JOptionPane.showMessageDialog(this,"No existe dieta");
            return;
        }
        ad.eliminarDieta(dieta.getIdDieta());
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero valido");
        }
                  
       
    }//GEN-LAST:event_jbEliminarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNueva;
    private javax.swing.JButton jbSalir;
    private com.toedter.calendar.JDateChooser jdFechaFinal;
    private com.toedter.calendar.JDateChooser jdFechaInicial;
    private javax.swing.JLabel jlDieta;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlPaciente;
    private javax.swing.JRadioButton jrEstado;
    private javax.swing.JTextField jtAltura;
    private javax.swing.JTextField jtGenero;
    private javax.swing.JTextField jtId;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtPaciente;
    private javax.swing.JTextField jtPesoBuscado;
    private javax.swing.JTextField jtPesoFinal;
    private javax.swing.JTextField jtPesoInicial;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
     VistaPrincipalMenu bpn = new VistaPrincipalMenu();
            bpn.setVisible(true);
                
    }
}

