/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Juan
 */
public class Nuestro_equipo extends javax.swing.JPanel {

    /**
     * Creates new form Nuestro_equipo
     */
    public Nuestro_equipo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Correo1 = new javax.swing.JLabel();
        Correo3 = new javax.swing.JLabel();
        jbVolver = new javax.swing.JButton();
        Correo4 = new javax.swing.JLabel();
        Correo2 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        Contenido = new javax.swing.JPanel();

        setLayout(null);

        Correo1.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        Correo1.setText("(fasegyra@gmail.com)");
        add(Correo1);
        Correo1.setBounds(210, 410, 230, 30);

        Correo3.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        Correo3.setText("(juank.Alvarez004@gmail.com)");
        add(Correo3);
        Correo3.setBounds(270, 500, 300, 30);

        jbVolver.setBackground(java.awt.SystemColor.activeCaption);
        jbVolver.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jbVolver.setText("Volver");
        jbVolver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverActionPerformed(evt);
            }
        });
        add(jbVolver);
        jbVolver.setBounds(590, 540, 110, 40);

        Correo4.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        Correo4.setText("(eglezalazar@gmail.com)");
        add(Correo4);
        Correo4.setBounds(200, 450, 270, 20);

        Correo2.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        Correo2.setText("(gustavo_02_16@hotmail.com)");
        add(Correo2);
        Correo2.setBounds(220, 470, 350, 30);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/pineapple-867245_1280.jpg"))); // NOI18N
        add(Fondo);
        Fondo.setBounds(0, 0, 1010, 850);

        Contenido.setLayout(null);
        add(Contenido);
        Contenido.setBounds(0, 0, 1000, 660);
    }// </editor-fold>//GEN-END:initComponents

    private void jbVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverActionPerformed
    
        PanelPorDefecto bpm = new PanelPorDefecto();
        ShowPanel(bpm);
    }//GEN-LAST:event_jbVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenido;
    private javax.swing.JLabel Correo1;
    private javax.swing.JLabel Correo2;
    private javax.swing.JLabel Correo3;
    private javax.swing.JLabel Correo4;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton jbVolver;
    // End of variables declaration//GEN-END:variables

private void ShowPanel(JPanel panel) {

        panel.setSize(1000, 650);
        panel.setLocation(0, 0);

        Contenido.removeAll();
        Contenido.add(panel, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }


}
