/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

/**
 *
 * @author Usuario
 */
public class PanelPorDefecto extends javax.swing.JPanel {

    /**
     * Creates new form PanelPorDefecto
     */
    public PanelPorDefecto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Fondo2 = new javax.swing.JLabel();

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/italian-cuisine-2378729_1280.jpg"))); // NOI18N

        setPreferredSize(new java.awt.Dimension(1000, 680));
        setLayout(null);

        jPanel2.setPreferredSize(new java.awt.Dimension(1050, 680));
        jPanel2.setLayout(null);

        Fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/italian-cuisine-2378729_1280.jpg"))); // NOI18N
        jPanel2.add(Fondo2);
        Fondo2.setBounds(0, 0, 1050, 680);

        add(jPanel2);
        jPanel2.setBounds(0, 0, 1050, 660);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Fondo2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
