/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Juan
 */
public class PanelNuestroEquipo extends javax.swing.JPanel {

    /**
     * Creates new form PanelNuestroEquipo
     */
    public PanelNuestroEquipo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenido = new javax.swing.JPanel();
        jbVolver = new javax.swing.JButton();
        Correo_1 = new javax.swing.JLabel();
        Correo_2 = new javax.swing.JLabel();
        Correo_3 = new javax.swing.JLabel();
        Correo_4 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        Fondo1 = new javax.swing.JLabel();

        setLayout(null);

        Contenido.setLayout(null);

        jbVolver.setBackground(java.awt.SystemColor.activeCaption);
        jbVolver.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jbVolver.setText("Volver");
        jbVolver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverActionPerformed(evt);
            }
        });
        Contenido.add(jbVolver);
        jbVolver.setBounds(590, 540, 110, 40);

        Correo_1.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        Correo_1.setText("(fasegyra@gmail.com)");
        Contenido.add(Correo_1);
        Correo_1.setBounds(220, 420, 220, 20);

        Correo_2.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        Correo_2.setText("(eglezalazar@gmail.com)");
        Contenido.add(Correo_2);
        Correo_2.setBounds(210, 450, 240, 20);

        Correo_3.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        Correo_3.setText("(gustavo_02_16@hotmail.com)");
        Contenido.add(Correo_3);
        Correo_3.setBounds(220, 475, 310, 23);

        Correo_4.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        Correo_4.setText("(juank.Alvarez004@gmail.com)");
        Contenido.add(Correo_4);
        Correo_4.setBounds(270, 500, 300, 20);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/pineapple-867245_1280.jpg"))); // NOI18N
        Contenido.add(Fondo);
        Fondo.setBounds(0, 0, 1010, 850);

        Fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/pineapple-867245_1280.jpg"))); // NOI18N
        Contenido.add(Fondo1);
        Fondo1.setBounds(0, 0, 1010, 850);

        add(Contenido);
        Contenido.setBounds(0, 0, 1010, 850);
    }// </editor-fold>//GEN-END:initComponents

    private void jbVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverActionPerformed

        PanelPorDefecto bpm = new PanelPorDefecto();
        ShowPanel(bpm);
    }//GEN-LAST:event_jbVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenido;
    private javax.swing.JLabel Correo_1;
    private javax.swing.JLabel Correo_2;
    private javax.swing.JLabel Correo_3;
    private javax.swing.JLabel Correo_4;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Fondo1;
    private javax.swing.JButton jbVolver;
    // End of variables declaration//GEN-END:variables

private void ShowPanel(JPanel panel) {

        panel.setSize(1000, 650);
        panel.setLocation(0, 0);

        Contenido.removeAll();
        Contenido.add(panel, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }





}
